add: ERC-721 tokens minting
dev-protocol/docs.devprotocol.xyz pull request #288
Opened 2022-10-23 21:37 UTC by KukretiShubham

2022-11-09 01:57 UTC, aggre requested changes
Well written, but this has some code to change.

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +	)
To deposit DEV on any Property, the contract will request pre-approval of DEV. Dev Kit has a comprehensive API to handle that. This example should be shown that, I think.

For example...

```ts
import { positionsCreate } from '@devprotocol/dev-kit/agent'
import { whenDefined } from '@devprotocol/util-ts'
import type { BaseProvider } from '@ethersproject/providers'

// This function mints an ERC-721 tokens by staking the specified staking amount to specified property, and returns the new tokenId.
export default (provider: BaseProvider) => {
	const from = (provider as Web3Provider).getSigner().getAddress()
	const start = await positionsCreate({
		provider,
		from,
		// Property address
		destination: '0xDbc05b1eCB4fdaEf943819C0B04e9ef6df4bAbd6',
		// Staking Value in Multiple of 10^18
		amount: '1000000000000000000',
		// Payload
		payload: '0x7468697320697320616e206578616d706c650000000000000000000000000000'
	})
	// When approval is needed, start.approvalNeeded is true, and start.approveIfNeeded does send the approval transaction. When approval is not needed, start.approvalNeeded is false, and start.approveIfNeeded does not send anything
	const approveIfNeeded = await whenDefined(start, (x) => x.approveIfNeeded())
	// When approval is needed, approveIfNeeded.waitNeeded is true, and start.waitOrSkipApproval does wait until confirmed the transaction. When approval is not needed, approveIfNeeded.waitNeeded is false, and start.waitOrSkipApproval does not do anything and resolve immediately
	const waitOrSkipApproval = await whenDefined(approveIfNeeded, (x) => x.waitOrSkipApproval())
    
	const stake = await whenDefined(waitOrSkipApproval, (x) => x.run())
	const staked = await whenDefined(stake, (x) => x.wait())
	// Staking transaction confirmed on-chain!
	...
```

And, there is the same example here too: https://docs.devprotocol.xyz/developers/use-cases/stokens/staking-bearing-nfts-as-your-collectibles#staking

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +	)
I've created a replit for writing a ts example: https://replit.com/@aggre/DevKitJS#index.ts

It should be helped out your writing an example with type assists.

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +```
👍

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +}
In Ethereum L1, It should use IAddressConfig, as same as https://docs.devprotocol.xyz/developers/use-cases/property-tokens/erc20-tokens-minting

```solidity
import "@devprotocol/protocol/contracts/interface/IPropertyFactory.sol"
import "@devprotocol/protocol/contracts/interface/IAddressConfig.sol"

contract MyContract {
    IAddressConfig public addressConfig;

    constructor(address _addressConfig) public {
        addressConfig = IAddressConfig(_addressConfig);
    }

    // This function mints an ERC-20 tokens with hard-coded options, and returns the new token address.
    function mint() external returns(address) {
        IPropertyFactory propertyFactory = addressConfig.propertyFactory();
        address tokens = propertyFactory.create(
            // Token name
            "My Token",
            // Token symbol
            "MYT",
            // Author address
            "0xDbc05b1eCB4fdaEf943819C0B04e9ef6df4bAbd6"
        );
        return tokens;
    }
}
```

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-royalty.md
> +
Many mutation query returns `TransactionResponse` (https://docs.ethers.io/v5/api/providers/types/#providers-TransactionResponse) not TransactionReceipt.

And this example has the subsequent process in the under row, so it should wait until resolve the TransactionResponse.

For example...

```ts
    const set = await whenDefined(sToken, (contract) =>
        contract.setSTokenRoyaltyForProperty(
            // Property address
            '0xDbc05b1eCB4fdaEf943819C0B04e9ef6df4bAbd6',
            // Royalty value (between 0 to 100)
            '10'
        )
    )
    await set.wait()
```

2022-11-09 01:57 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-royalty.md
> +```
As same as the Ethereum example of `versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md`, this should be used IAddressConfig.

2022-11-13 19:32 UTC, KukretiShubham commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +```
Well I didn't investigate earlier but, depositToProperty from an external contract would be a little problematic. 

If we see at the function structure
```solidity 
	function depositToProperty(
		address _property,
		uint256 _amount,
		bytes32 _payload
	) external override returns (uint256) {
		return _implDepositToProperty(_property, _amount, _payload);
	}

	function _implDepositToProperty(
		address _property,
		uint256 _amount,
		bytes32 _payload
	) private onlyAuthenticatedProperty(_property) returns (uint256) {
		/**
		 * Gets the latest cumulative sum of the interest price.
		 */
		(
			uint256 reward,
			uint256 holders,
			uint256 interest,
			uint256 holdersCap
		) = calculateCumulativeRewardPrices();
		/**
		 * Saves variables that should change due to the addition of staking.
		 */
		updateValues(
			true,
			_property,
			_amount,
			RewardPrices(reward, holders, interest, holdersCap)
		);
		/**
		 * transfer dev tokens
		 */
		require(
			IERC20(registry().registries("Dev")).transferFrom(
				msg.sender,
				_property,
				_amount
			),
			"dev transfer failed"
		);
		/**
		 * mint s tokens
		 */
		ISTokensManager sTokenManager = ISTokensManager(
			registry().registries("STokensManager")
		);
		if (sTokenManager.positionsOfProperty(_property).length == 0) {
			lockedupProperties.add(_property);
		}
		uint256 tokenId = sTokenManager.mint(
			msg.sender,
			_property,
			_amount,
			interest,
			_payload
		);
		emit Lockedup(msg.sender, _property, _amount, tokenId);

		return tokenId;
	}
```
It treats `msg.sender` as DEV holder. In above example, 
- msg.sender would be the above external contract.
- The external contract itself needs to hold the tokens and approve the spendings for lockup contract. 
- Then, transfer the minted SToken back to the tx.origin(orginal msg.sender). 

Hence I commented the code as to be updated... for now.

2022-11-13 19:33 UTC, KukretiShubham commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +}
same here 
https://github.com/dev-protocol/docs.devprotocol.xyz/pull/288#discussion_r1020952558

2022-11-13 19:33 UTC, KukretiShubham commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-royalty.md
> +
doen

2022-11-13 19:33 UTC, KukretiShubham commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-royalty.md
> +```
done

2022-11-15 08:05 UTC, aggre approved these changes
LGTM!

2022-11-15 08:19 UTC, aggre commented on versioned_docs/version-0.1.0/developers/use-cases/stokens/erc721-tokens-minting.md
> +```
> It treats `msg.sender` as DEV holder. In above example,
> 
>     * msg.sender would be the above external contract.
> 
>     * The external contract itself needs to hold the tokens and approve the spendings for lockup contract.
> 
>     * Then, transfer the minted SToken back to the tx.origin(orginal msg.sender).
> 
> 
> Hence I commented the code as to be updated... for now.

As you mentioned, staking via an external contract requires the external contract to act as a staker.

Now let's see if `depositToProperty` can handle an explicit address instead of `msg.sender`. I think it's possible, but it's also dangerous. Some users set a maximum allowance to save gas, and indeed Dev Kit has an interface for overriding the allowance (i.e. setting the maximum instead of the just required amount). If `depositToProperty` handles an explicit address, it may allow unintended staking.

2022-12-08 04:08 UTC, merged